//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidWebService.Models
{
    using Newtonsoft.Json;
    
    public partial class CTDatPhong
    {
        public System.DateTime NgayDat { get; set; }
        public string GhiChu { get; set; }
        public double TienCoc { get; set; }
        public int MaPT { get; set; }
        public string TenDangNhap { get; set; }
        [JsonIgnore]
        public virtual TaiKhoan TaiKhoan { get; set; }
        [JsonIgnore]
        public virtual PhongTro PhongTro { get; set; }
    }
}
