//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidWebService.Models
{
    using System;
    using Newtonsoft.Json;

    public partial class NguoiDung
    {
        public string CCCD { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public Nullable<DateTime> NgaySinh { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string TenDangNhap { get; set; }

        [JsonIgnore]
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
