//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidWebService.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using AndroidWebService.Models.Enums;
    using System.Diagnostics.CodeAnalysis;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PhongTro
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongTro()
        {
            this.HinhAnh = string.Empty;
            this.NgayDang = DateTime.Now;
            this.GiaoDich = new HashSet<GiaoDich>();
            this.MotelMedia = new HashSet<MotelMedia>();
            this.PTYeuThich = new HashSet<PTYeuThich>();
            this.MaTT = (short)MotelStatus.Available;
        }
    
        public int MaPT { get; set; }
        public string TieuDe { get; set; }
        public DateTime NgayDang { get; set; }
        public double DienTich { get; set; }
        public double SoTien { get; set; }
        public Nullable<double> TienCoc { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        [NotMapped]
        public string ShortText
        {
            get
            {
                string shortText = string.Empty;
                int textLength = this.MoTa.Length;
                if (textLength >= 30)
                {
                    for (int i = 0; i < (int)(textLength / 2); i++)
                    {
                        shortText += this.MoTa[i];
                    }
                    shortText += "...";

                    return shortText;
                }

                return this.MoTa;
            }
        }
        [NotMapped]
        public string Base64Thumbnail { get; set; }
        public string DiaChi { get; set; }
        public string TenDangNhap { get; set; }
        public int MaVT { get; set; }
        public int MaTT { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<GiaoDich> GiaoDich { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotelMedia> MotelMedia { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PTYeuThich> PTYeuThich { get; set; }
        public virtual TTPhongTro TTPhongTro { get; set; }
        public virtual ViTri ViTri { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
