//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidWebService.Models
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PhongTro
    {
        public static readonly string SERVER_IMG_PATH = "~/Resources/Pictures/";
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongTro()
        {
            this.GiaoDich = new HashSet<GiaoDich>();
            this.PTYeuThich = new HashSet<PTYeuThich>();
        }
    
        public int MaPT { get; set; }
        public string TieuDe { get; set; }
        public DateTime NgayDang { get; set; }
        public double DienTich { get; set; }
        public double SoTien { get; set; }
        public Nullable<double> TienCoc { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        [NotMapped]
        public string Base64Image { get; set; }
        public string DiaChi { get; set; }
        public string TenDangNhap { get; set; }
        public int MaVT { get; set; }
        public int MaTT { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDich> GiaoDich { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PTYeuThich> PTYeuThich { get; set; }
        public virtual TTPhongTro TTPhongTro { get; set; }
        public virtual ViTri ViTri { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
