//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidWebService.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class PhongTro
    {
        public static string SERVER_IMG_PATH = "~/Resources/Pictures/";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongTro()
        {
            this.NgayDang = DateTime.Now;
            this.CTDatPhong = new HashSet<CTDatPhong>();
        }
    
        public int MaPT { get; set; }
        public string TieuDe { get; set; }
        public string HinhAnh { get; set; }
        public DateTime NgayDang { get; set; }
        public string MoTa { get; set; }
        public int DienTich { get; set; }
        public int Gia { get; set; }
        public string TenDangNhap { get; set; }
        public int MaVT { get; set; }
        public int MaTT { get; set; }
        [NotMapped]
        [JsonIgnore]
        public string UserAvatarBase64String { get; set; }

        [JsonIgnore]
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<CTDatPhong> CTDatPhong { get; set; }
        [JsonIgnore]
        public virtual TaiKhoan TaiKhoan { get; set; }
        [JsonIgnore]
        public virtual TrangThai TrangThai { get; set; }
        [JsonIgnore]
        public virtual ViTri ViTri { get; set; }
    }
}
