//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTYeuThich
    {
        public string GhiChu { get; set; }
        public int MaPT { get; set; }
        public string TenDangNhap { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual PhongTro PhongTro { get; set; }
    }
}
