//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidWebService.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.CTDatPhong = new HashSet<CTDatPhong>();
            this.PhongTro = new HashSet<PhongTro>();
        }
    
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
        public int MaVaiTro { get; set; }
        public string CCCD { get; set; }

        public void TrimAccount()
        {
            this.TenDangNhap = this.TenDangNhap.Trim();
            this.Email = this.Email.Trim();
            this.SoDT = this.SoDT.Trim();
            this.CCCD = this.CCCD.Trim();
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<CTDatPhong> CTDatPhong { get; set; }
        [JsonIgnore]
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PhongTro> PhongTro { get; set; }
        [JsonIgnore]
        public virtual VaiTro VaiTro { get; set; }
    }
}
