//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidWebService.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TaiKhoan
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.CCCD = string.Empty;
            this.StrAvatar = string.Empty;
            this.Base64Avatar = string.Empty;
            this.GiaoDich = new HashSet<GiaoDich>();
            this.PTYeuThich = new HashSet<PTYeuThich>();
            this.PhongTro = new HashSet<PhongTro>();
        }
    
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
        public string StrAvatar { get; set; }
        [NotMapped]
        public string Base64Avatar { get; set; } 
        public int MaVaiTro { get; set; }
        public string CCCD { get; set; }

        public virtual NguoiDung NguoiDung { get; set; }
        public virtual VaiTro VaiTro { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<GiaoDich> GiaoDich { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PTYeuThich> PTYeuThich { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PhongTro> PhongTro { get; set; }
    }
}
